### ISSUE TITLE
PAT required for push to Github 

### ISSUE THREAD

**Issue by Donica-commits** [learn-co-curriculum/dsc-git-practice#2]
I think it would be helpful to let students know in this lesson that they will need a Personal Authentication Token to move files from a local directory to Github from here on out.
![push_PAT_Github](https://user-images.githubusercontent.com/87505757/129501782-4ef198f3-b1cf-4b9e-b563-a002c11b0968.PNG)

**Comment by jilliankim** [comment]
Please use this doc for setting up git first then start with git practices. https://docs.google.com/document/d/1H-3EU7yDj8S9FefEq5_GpRoltvFk90A7THh6PIZwp7A/edit
